
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudentFinalProject.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
public partial class teacher1
{

    public int id { get; set; }

    public string name { get; set; }

    public string course { get; set; }
        [DisplayName("Upload File")]
    public string photo { get; set; }
    public HttpPostedFileBase ImageFile { get; set; }
}

}
